/* eslint-disable @typescript-eslint/no-unused-vars */
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { ThemeProvider } from "@/components/theme-provider"
import type { Metadata } from "next";
import { Geist, Geist_Mono, Oswald, Racing_Sans_One } from "next/font/google"; // Racing_Sans_One is the F1 font
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// 1. Initialize the F1 font
const f1Font = Racing_Sans_One({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "f1",
  description: "Generated by create next app",
};
const oswald = Oswald({
  subsets: ["latin"],
  weight: ["300", "700"], // 700 gives it that bold F1 look
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en" suppressHydrationWarning>
      {/* 2. Using f1Font.className makes it the default for EVERYTHING inside the body */}
      <body
        className={`${oswald.className} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
      </body>
    </html>
    
    </ClerkProvider>
  );
}